<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1678719958902" stop="1678719991969" version="1.4.0">
    <name>All Test Suite</name>
    <test-cases>
        <test-case start="1678719971418" stop="1678719972986" status="passed">
            <name>loginErrorValidation</name>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
        <test-case start="1678719972520" stop="1678719979802" status="passed">
            <name>standAlonTest</name>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
        <test-case start="1678719984628" stop="1678719988105" status="failed">
            <name>productErrorValidation</name>
            <failure>
                <message>AssertionError: expected [true] but found [false]</message>
                <stack-trace>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at AyanMustafaPackage.Tests.errorValidationsTest.productErrorValidation(errorValidationsTest.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
        <test-case start="1678719989954" stop="1678719991282" status="passed">
            <name>orderStoryTest</name>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="feature" value="C:/desktop/SeleniumFrameworkDesign"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
